apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nexpay-prd

resources:
- ../../base

namePrefix: prd-

images:
- name: nexpay-payments
  newName: nexpay-payments
  newTag: latest


replicas:
- count: 2
  name: prd-payments
labels:
- includeSelectors: true
  pairs:
    environment: prd