mode: deployment

image:
  repository: otel/opentelemetry-collector-k8s
  tag: "0.161.0"

command:
  name: otelcol-k8s

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

config:
  extensions:
    health_check:
      endpoint: ${env:MY_POD_IP}:13133

  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:4317
        http:
          endpoint: ${env:MY_POD_IP}:4318

  processors:
    memory_limiter:
      check_interval: 5s
      limit_percentage: 80
      spike_limit_percentage: 25

    batch: {}

  exporters:
    debug:
      verbosity: basic

  service:
    extensions:
      - health_check

    pipelines:
      traces:
        receivers:
          - otlp
        processors:
          - memory_limiter
          - batch
        exporters:
          - debug