name: Build Images

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ROLE_ARN: ${{ vars.AWS_GITHUB_ACTIONS_ROLE_ARN }}

  PAYMENTS_REPOSITORY: nexpay/dev/payments
  FRONTEND_REPOSITORY: nexpay/dev/frontend

jobs:
  build-and-push:
    name: Build and Push Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Validate AWS configuration
        run: |
          if [ -z "${AWS_REGION}" ]; then
            echo "AWS_REGION repository variable is not configured."
            exit 1
          fi

          if [ -z "${AWS_ROLE_ARN}" ]; then
            echo "AWS_GITHUB_ACTIONS_ROLE_ARN repository variable is not configured."
            exit 1
          fi

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_ARN }}

      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.0

      - name: Build and push Payments image
        uses: docker/build-push-action@v7.4.0
        with:
          context: ./application/payments
          push: true
          tags: |
            ${{ steps.ecr.outputs.registry }}/${{ env.PAYMENTS_REPOSITORY }}:${{ github.sha }}

      - name: Build and push Frontend image
        uses: docker/build-push-action@v7.4.0
        with:
          context: ./application/frontend
          push: true
          tags: |
            ${{ steps.ecr.outputs.registry }}/${{ env.FRONTEND_REPOSITORY }}:${{ github.sha }}